[package]
name = "after"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
teloxide = { workspace = true }
sqlx = { workspace = true }
rand = { workspace = true }
dotenvy = { workspace = true }
